[package]
name = "iex_feed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap-parser = { version = "0.14.0", features = ["data"] }
bytes = { version = "1.2.1" }
hex = "0.4.3"
byteorder = "1.4.3"